error <- function(...) {
  stop(..., call. = FALSE)
}
